// Automatically generated by the GraphQL Codegen
// Please do not modify it manually
// Run 'yarn graphql-codegen' to update or regenerate

import { DocumentNode } from '@apollo/client';
import gql from 'graphql-tag';

export const CREATE_PROGRAM_MUTATION: DocumentNode = gql`
  mutation CreateProgram($description: String!) {
    createProgram(description: $description) {
      id
      description
      files {
        path
        rationale
        generationStatus
        content
      }
      sharedDependencies {
        name
        description
        symbols
      }
    }
  }
`;

export const REGENERATE_PROGRAM_MUTATION: DocumentNode = gql`
  mutation RegenerateProgram($input: RegenerateProgramInput!) {
    regenerateProgram(input: $input) {
      id
      description
      files {
        path
        rationale
        generationStatus
        content
      }
      sharedDependencies {
        name
        description
        symbols
      }
    }
  }
`;

export const OBSERVE_PROGRAM_SUBSCRIPTION: DocumentNode = gql`
  subscription ObserveProgram($id: ID!) {
    observeProgram(id: $id) {
      id
      description
      files {
        path
        rationale
        generationStatus
        content
      }
      sharedDependencies {
        name
        description
        symbols
      }
    }
  }
`;
